//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMSShipIOTool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMSShipIOTool.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Base ID: .
        /// </summary>
        internal static string _基地ID_ {
            get {
                return ResourceManager.GetString("_基地ID_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Seed: .
        /// </summary>
        internal static string _种子_ {
            get {
                return ResourceManager.GetString("_种子_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Type: .
        /// </summary>
        internal static string _类型_ {
            get {
                return ResourceManager.GetString("_类型_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Name: .
        /// </summary>
        internal static string _飞船名_ {
            get {
                return ResourceManager.GetString("_飞船名_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///Version 1.3.0
        ///Author: 蓝夜深空 (BNDS-tx)
        ///
        ///
        ///This software is for communicate and study only.
        ///NMS Ship IO Tool  Copyright (C) 2026  徐腾（蓝夜深空）.
        /// </summary>
        internal static string AboutDialog_info_Text {
            get {
                return ResourceManager.GetString("AboutDialog.info.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutDialog_this_Text {
            get {
                return ResourceManager.GetString("AboutDialog.this.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMS Ship IO Tool
        ///无人深空飞船导入导出工具.
        /// </summary>
        internal static string AboutDialog_title_Text {
            get {
                return ResourceManager.GetString("AboutDialog.title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Form1_aboutButton_Text {
            get {
                return ResourceManager.GetString("Form1.aboutButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Form1_buttonExport_Text {
            get {
                return ResourceManager.GetString("Form1.buttonExport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Tech., Module.
        /// </summary>
        internal static string Form1_buttonExportShipTech_Text {
            get {
                return ResourceManager.GetString("Form1.buttonExportShipTech.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Tech., Module.
        /// </summary>
        internal static string Form1_buttonExportShipTechI_Text {
            get {
                return ResourceManager.GetString("Form1.buttonExportShipTechI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Form1_buttonImport_Text {
            get {
                return ResourceManager.GetString("Form1.buttonImport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tech., Module.
        /// </summary>
        internal static string Form1_buttonImportShipTech_Text {
            get {
                return ResourceManager.GetString("Form1.buttonImportShipTech.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tech., Module.
        /// </summary>
        internal static string Form1_buttonImportShipTechI_Text {
            get {
                return ResourceManager.GetString("Form1.buttonImportShipTechI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Form1_buttonLoad_Text {
            get {
                return ResourceManager.GetString("Form1.buttonLoad.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Form1_buttonSeedShipExport_Text {
            get {
                return ResourceManager.GetString("Form1.buttonSeedShipExport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Form1_buttonSeedShipImport_Text {
            get {
                return ResourceManager.GetString("Form1.buttonSeedShipImport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Path.
        /// </summary>
        internal static string Form1_buttonSelect_Text {
            get {
                return ResourceManager.GetString("Form1.buttonSelect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Seed.
        /// </summary>
        internal static string Form1_buttonSetSeed_Text {
            get {
                return ResourceManager.GetString("Form1.buttonSetSeed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Obf..
        /// </summary>
        internal static string Form1_checkBoxI_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import as new ship.
        /// </summary>
        internal static string Form1_checkBoxNewShip_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxNewShip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use .nmsship.
        /// </summary>
        internal static string Form1_checkBoxNMSSHIP1_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxNMSSHIP1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use .nmsship.
        /// </summary>
        internal static string Form1_checkBoxNMSSHIP3_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxNMSSHIP3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Obf..
        /// </summary>
        internal static string Form1_checkBoxS_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as .sh0.
        /// </summary>
        internal static string Form1_checkBoxSH0_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxSH0.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Tech., Module as .tech.
        /// </summary>
        internal static string Form1_checkBoxTech_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxTech.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Tech., Module as .tech.
        /// </summary>
        internal static string Form1_checkBoxTechI_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxTechI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Path.
        /// </summary>
        internal static string Form1_exportSelect_Text {
            get {
                return ResourceManager.GetString("Form1.exportSelect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        internal static string Form1_importSelect_Text {
            get {
                return ResourceManager.GetString("Form1.importSelect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Objects content manually:.
        /// </summary>
        internal static string Form1_inputTextI_Text {
            get {
                return ResourceManager.GetString("Form1.inputTextI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please adhere to the JSON format.
        /// </summary>
        internal static string Form1_inputTextIExplanation_Text {
            get {
                return ResourceManager.GetString("Form1.inputTextIExplanation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file name:.
        /// </summary>
        internal static string Form1_label1_Text {
            get {
                return ResourceManager.GetString("Form1.label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save path:.
        /// </summary>
        internal static string Form1_labelPath_Text {
            get {
                return ResourceManager.GetString("Form1.labelPath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file name:.
        /// </summary>
        internal static string Form1_nameTextE_Text {
            get {
                return ResourceManager.GetString("Form1.nameTextE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file path:.
        /// </summary>
        internal static string Form1_pathTextE_Text {
            get {
                return ResourceManager.GetString("Form1.pathTextE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file path:.
        /// </summary>
        internal static string Form1_pathTextI_Text {
            get {
                return ResourceManager.GetString("Form1.pathTextI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your starship:.
        /// </summary>
        internal static string Form1_seedSelectText_Text {
            get {
                return ResourceManager.GetString("Form1.seedSelectText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Export youe ship here:.
        /// </summary>
        internal static string Form1_seedShipIOText_Text {
            get {
                return ResourceManager.GetString("Form1.seedShipIOText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Seed: .
        /// </summary>
        internal static string Form1_seedText_Text {
            get {
                return ResourceManager.GetString("Form1.seedText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your Corvette:.
        /// </summary>
        internal static string Form1_shipSelectI_Text {
            get {
                return ResourceManager.GetString("Form1.shipSelectI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Info..
        /// </summary>
        internal static string Form1_tabPage1_Text {
            get {
                return ResourceManager.GetString("Form1.tabPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corvettes.
        /// </summary>
        internal static string Form1_tabPage2_Text {
            get {
                return ResourceManager.GetString("Form1.tabPage2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starships.
        /// </summary>
        internal static string Form1_tabPage3_Text {
            get {
                return ResourceManager.GetString("Form1.tabPage3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMS Ship IO Tool.
        /// </summary>
        internal static string Form1_this_Text {
            get {
                return ResourceManager.GetString("Form1.this.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new Corvette is not currently supported..
        /// </summary>
        internal static string 不支持添加新自定义飞船 {
            get {
                return ResourceManager.GetString("不支持添加新自定义飞船", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected or unsupported file format!.
        /// </summary>
        internal static string 不支持的文件格式 {
            get {
                return ResourceManager.GetString("不支持的文件格式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two import sources are configured. Please keep only one!.
        /// </summary>
        internal static string 两个导入来源 {
            get {
                return ResourceManager.GetString("两个导入来源", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 valid save found: .
        /// </summary>
        internal static string 仅找到一个存档_自动选择 {
            get {
                return ResourceManager.GetString("仅找到一个存档_自动选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Selected.
        /// </summary>
        internal static string 使用选中路径 {
            get {
                return ResourceManager.GetString("使用选中路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Saving Time: .
        /// </summary>
        internal static string 最后保存时间 {
            get {
                return ResourceManager.GetString("最后保存时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string 切换语言按钮 {
            get {
                return ResourceManager.GetString("切换语言按钮", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar.
        /// </summary>
        internal static string 太阳帆 {
            get {
                return ResourceManager.GetString("太阳帆", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save loaded successfully..
        /// </summary>
        internal static string 存档加载完成 {
            get {
                return ResourceManager.GetString("存档加载完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform: .
        /// </summary>
        internal static string 存档平台 {
            get {
                return ResourceManager.GetString("存档平台", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your save may be outdated or corrupted. Please run the game to refresh it, or use another tool to inspect it..
        /// </summary>
        internal static string 存档损坏提示 {
            get {
                return ResourceManager.GetString("存档损坏提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for saves failed, with error: .
        /// </summary>
        internal static string 寻找存档失败_错误信息 {
            get {
                return ResourceManager.GetString("寻找存档失败_错误信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import successful!.
        /// </summary>
        internal static string 导入成功 {
            get {
                return ResourceManager.GetString("导入成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exported successfully: .
        /// </summary>
        internal static string 导出文件成功 {
            get {
                return ResourceManager.GetString("导出文件成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seed entered! Please input a seed to set the ship..
        /// </summary>
        internal static string 尚未输入种子 {
            get {
                return ResourceManager.GetString("尚未输入种子", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ship selected for export!.
        /// </summary>
        internal static string 尚未选择要导出的飞船 {
            get {
                return ResourceManager.GetString("尚未选择要导出的飞船", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ship selected! Please select the ship you want to configure..
        /// </summary>
        internal static string 尚未选择飞船 {
            get {
                return ResourceManager.GetString("尚未选择飞船", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following possible save directories were detected automatically:.
        /// </summary>
        internal static string 已自动识别目录 {
            get {
                return ResourceManager.GetString("已自动识别目录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic.
        /// </summary>
        internal static string 异星 {
            get {
                return ResourceManager.GetString("异星", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for loading.
        /// </summary>
        internal static string 待加载 {
            get {
                return ResourceManager.GetString("待加载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter.
        /// </summary>
        internal static string 战斗 {
            get {
                return ResourceManager.GetString("战斗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Manually.
        /// </summary>
        internal static string 手动选择 {
            get {
                return ResourceManager.GetString("手动选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauler.
        /// </summary>
        internal static string 托运 {
            get {
                return ResourceManager.GetString("托运", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor.
        /// </summary>
        internal static string 护卫 {
            get {
                return ResourceManager.GetString("护卫", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized.
        /// </summary>
        internal static string 拼接 {
            get {
                return ResourceManager.GetString("拼接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string 探险家 {
            get {
                return ResourceManager.GetString("探险家", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled!.
        /// </summary>
        internal static string 操作取消 {
            get {
                return ResourceManager.GetString("操作取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist!.
        /// </summary>
        internal static string 文件不存在 {
            get {
                return ResourceManager.GetString("文件不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content cannot be parsed!.
        /// </summary>
        internal static string 文件内容无法解析 {
            get {
                return ResourceManager.GetString("文件内容无法解析", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported File (*.json; *.sh0; *.nmsship; *.tech)|*.json; *.sh0; *.nmsship; *.tech|All (*.*)|*.
        /// </summary>
        internal static string 文件筛选内容A {
            get {
                return ResourceManager.GetString("文件筛选内容A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported File (*.json; *.nmsship; *.tech)|*.json; *.nmsship; *.tech|All (*.*)|*.
        /// </summary>
        internal static string 文件筛选内容BS {
            get {
                return ResourceManager.GetString("文件筛选内容BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported File (*.json; *.sh0; *.nmsship)|*.json; *.sh0; *.nmsship|All (*.*)|*.
        /// </summary>
        internal static string 文件筛选内容S {
            get {
                return ResourceManager.GetString("文件筛选内容S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported File (*.json; *.tech)|*.json; *.tech|All (*.*)|*.
        /// </summary>
        internal static string 文件筛选内容T {
            get {
                return ResourceManager.GetString("文件筛选内容T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content has been selected for import or entered yet! \nPlease select the file you wish to import or manually input the content to be imported!.
        /// </summary>
        internal static string 无导入内容 {
            get {
                return ResourceManager.GetString("无导入内容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import a regular ship into a Corvette slot!
        ///Please import a full Corvette .nmsship file, or select a starship slot..
        /// </summary>
        internal static string 无法导入普通船到自定义飞船 {
            get {
                return ResourceManager.GetString("无法导入普通船到自定义飞船", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starships: .
        /// </summary>
        internal static string 普通飞船_ {
            get {
                return ResourceManager.GetString("普通飞船_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string 未命名 {
            get {
                return ResourceManager.GetString("未命名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No export path selected or the path is invalid!.
        /// </summary>
        internal static string 未选择导出路径或路径无效 {
            get {
                return ResourceManager.GetString("未选择导出路径或路径无效", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid save found.
        /// </summary>
        internal static string 没有找到有效的存档 {
            get {
                return ResourceManager.GetString("没有找到有效的存档", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to disable obfuscation.
        ///Because NMS save files are obfuscated, importing and exporting plaintext content requires obfuscation and de-obfuscation. If your device runs NMS smoothly, the performance impact of obfuscation is negligible.
        ///Even if the content you import or export is already ciphertext, it is recommended to keep obfuscation enabled. The obfuscation algorithm does not affect already-obfuscated content and helps prevent accidental plaintext writes from corrupting your save.
        ///Are you s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string 混淆关闭警告I {
            get {
                return ResourceManager.GetString("混淆关闭警告I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to disable obfuscation.
        ///Because NMS save files are obfuscated, importing and exporting plaintext content requires obfuscation and de-obfuscation. If your device runs NMS smoothly, the performance impact of obfuscation is negligible.
        ///The obfuscation algorithm does not affect already-obfuscated content and helps prevent accidental plaintext writes from corrupting your save.
        ///Are you sure you want to disable obfuscation and export/import content directly?
        ///If so, please ensure the content you i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string 混淆关闭警告S {
            get {
                return ResourceManager.GetString("混淆关闭警告S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string 特殊船 {
            get {
                return ResourceManager.GetString("特殊船", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        internal static string 玩家存档 {
            get {
                return ResourceManager.GetString("玩家存档", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living.
        /// </summary>
        internal static string 生物 {
            get {
                return ResourceManager.GetString("生物", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string 确定 {
            get {
                return ResourceManager.GetString("确定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed Invalid.
        /// </summary>
        internal static string 种子无效 {
            get {
                return ResourceManager.GetString("种子无效", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corvette.
        /// </summary>
        internal static string 自定义护卫舰 {
            get {
                return ResourceManager.GetString("自定义护卫舰", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corvettes: .
        /// </summary>
        internal static string 自定义护卫舰_ {
            get {
                return ResourceManager.GetString("自定义护卫舰_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string 警告 {
            get {
                return ResourceManager.GetString("警告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed set successfully: .
        /// </summary>
        internal static string 设置种子成功 {
            get {
                return ResourceManager.GetString("设置种子成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option!.
        /// </summary>
        internal static string 请先选择一个选项 {
            get {
                return ResourceManager.GetString("请先选择一个选项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or enter the content to import first!.
        /// </summary>
        internal static string 请先选择或输入导入内容 {
            get {
                return ResourceManager.GetString("请先选择或输入导入内容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file path to import first!.
        /// </summary>
        internal static string 请先选择要导入文件路径 {
            get {
                return ResourceManager.GetString("请先选择要导入文件路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a path first, or click &quot;Pick Manually&quot;..
        /// </summary>
        internal static string 请先选择路径或手动选择 {
            get {
                return ResourceManager.GetString("请先选择路径或手动选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid seed!.
        /// </summary>
        internal static string 请输入有效种子 {
            get {
                return ResourceManager.GetString("请输入有效种子", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select An Option.
        /// </summary>
        internal static string 请选择一个选项 {
            get {
                return ResourceManager.GetString("请选择一个选项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Save Path.
        /// </summary>
        internal static string 请选择存档路径 {
            get {
                return ResourceManager.GetString("请选择存档路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data: .
        /// </summary>
        internal static string 读取数据时发生错误 {
            get {
                return ResourceManager.GetString("读取数据时发生错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path does not exist or is invalid..
        /// </summary>
        internal static string 路径不存在或无效 {
            get {
                return ResourceManager.GetString("路径不存在或无效", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty..
        /// </summary>
        internal static string 路径不能为空 {
            get {
                return ResourceManager.GetString("路径不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Save File.
        /// </summary>
        internal static string 选择一个存档 {
            get {
                return ResourceManager.GetString("选择一个存档", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string 错误 {
            get {
                return ResourceManager.GetString("错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input is not in valid JSON format!.
        /// </summary>
        internal static string 非法JSON格式 {
            get {
                return ResourceManager.GetString("非法JSON格式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship ID: .
        /// </summary>
        internal static string 飞船ID_ {
            get {
                return ResourceManager.GetString("飞船ID_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship tech, module and inventory data is abnormal and cannot be exported!.
        /// </summary>
        internal static string 飞船技术模块数据异常无法导出 {
            get {
                return ResourceManager.GetString("飞船技术模块数据异常无法导出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship data is empty and cannot be exported!.
        /// </summary>
        internal static string 飞船数据为空无法导出 {
            get {
                return ResourceManager.GetString("飞船数据为空无法导出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship data is abnormal and cannot be exported!.
        /// </summary>
        internal static string 飞船数据异常无法导出 {
            get {
                return ResourceManager.GetString("飞船数据异常无法导出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a new ship!
        ///Your ship slots are full..
        /// </summary>
        internal static string 飞船槽位已满 {
            get {
                return ResourceManager.GetString("飞船槽位已满", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle.
        /// </summary>
        internal static string 飞艇 {
            get {
                return ResourceManager.GetString("飞艇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tech_Module_Inventory.
        /// </summary>
        internal static string 默认导出技术文件名后缀 {
            get {
                return ResourceManager.GetString("默认导出技术文件名后缀", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportedShip.
        /// </summary>
        internal static string 默认导出文件名 {
            get {
                return ResourceManager.GetString("默认导出文件名", resourceCulture);
            }
        }
    }
}
