//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMSShipIOTool.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMSShipIOTool.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 版本 1.2.0
        ///作者：蓝夜深空（BNDS-tx）
        ///
        ///
        ///
        ///本工具仅供学习和交流使用。
        ///NMS Ship IO Tool  Copyright (C) 2025  徐腾（蓝夜深空） 的本地化字符串。
        /// </summary>
        internal static string AboutDialog_info_Text {
            get {
                return ResourceManager.GetString("AboutDialog.info.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string AboutDialog_this_Text {
            get {
                return ResourceManager.GetString("AboutDialog.this.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NMS Ship IO Tool
        ///无人深空飞船导入导出工具 的本地化字符串。
        /// </summary>
        internal static string AboutDialog_title_Text {
            get {
                return ResourceManager.GetString("AboutDialog.title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string Form1_aboutButton_Text {
            get {
                return ResourceManager.GetString("Form1.aboutButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出飞船 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonExport_Text {
            get {
                return ResourceManager.GetString("Form1.buttonExport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出飞船技术、模块与库存 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonExportShipTech_Text {
            get {
                return ResourceManager.GetString("Form1.buttonExportShipTech.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出飞船技术、模块与库存 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonExportShipTechI_Text {
            get {
                return ResourceManager.GetString("Form1.buttonExportShipTechI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入飞船 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonImport_Text {
            get {
                return ResourceManager.GetString("Form1.buttonImport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入飞船技术、模块与库存 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonImportShipTech_Text {
            get {
                return ResourceManager.GetString("Form1.buttonImportShipTech.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入飞船技术、模块与库存 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonImportShipTechI_Text {
            get {
                return ResourceManager.GetString("Form1.buttonImportShipTechI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载存档 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonLoad_Text {
            get {
                return ResourceManager.GetString("Form1.buttonLoad.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出飞船 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonSeedShipExport_Text {
            get {
                return ResourceManager.GetString("Form1.buttonSeedShipExport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入飞船 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonSeedShipImport_Text {
            get {
                return ResourceManager.GetString("Form1.buttonSeedShipImport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择路径 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonSelect_Text {
            get {
                return ResourceManager.GetString("Form1.buttonSelect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入种子 的本地化字符串。
        /// </summary>
        internal static string Form1_buttonSetSeed_Text {
            get {
                return ResourceManager.GetString("Form1.buttonSetSeed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用混淆 的本地化字符串。
        /// </summary>
        internal static string Form1_checkBoxI_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作为新飞船导入 的本地化字符串。
        /// </summary>
        internal static string Form1_checkBoxNewShip_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxNewShip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用完整包 的本地化字符串。
        /// </summary>
        internal static string Form1_checkBoxNMSSHIP1_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxNMSSHIP1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用完整包 的本地化字符串。
        /// </summary>
        internal static string Form1_checkBoxNMSSHIP3_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxNMSSHIP3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用混淆 的本地化字符串。
        /// </summary>
        internal static string Form1_checkBoxS_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为 .sh0 的本地化字符串。
        /// </summary>
        internal static string Form1_checkBoxSH0_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxSH0.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出技术、模块与库存为 .tech 的本地化字符串。
        /// </summary>
        internal static string Form1_checkBoxTech_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxTech.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出技术、模块与库存为 .tech 的本地化字符串。
        /// </summary>
        internal static string Form1_checkBoxTechI_Text {
            get {
                return ResourceManager.GetString("Form1.checkBoxTechI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择保存地址 的本地化字符串。
        /// </summary>
        internal static string Form1_exportSelect_Text {
            get {
                return ResourceManager.GetString("Form1.exportSelect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择导入文件 的本地化字符串。
        /// </summary>
        internal static string Form1_importSelect_Text {
            get {
                return ResourceManager.GetString("Form1.importSelect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或者你可以在此处手动输入导入内容（仅限 Objects 字段）： 的本地化字符串。
        /// </summary>
        internal static string Form1_inputTextI_Text {
            get {
                return ResourceManager.GetString("Form1.inputTextI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请遵守 JSON 格式，并确保在最外围包含中括号”[]“ 的本地化字符串。
        /// </summary>
        internal static string Form1_inputTextIExplanation_Text {
            get {
                return ResourceManager.GetString("Form1.inputTextIExplanation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件名： 的本地化字符串。
        /// </summary>
        internal static string Form1_label1_Text {
            get {
                return ResourceManager.GetString("Form1.label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档路径: 的本地化字符串。
        /// </summary>
        internal static string Form1_labelPath_Text {
            get {
                return ResourceManager.GetString("Form1.labelPath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出文件名： 的本地化字符串。
        /// </summary>
        internal static string Form1_nameTextE_Text {
            get {
                return ResourceManager.GetString("Form1.nameTextE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出文件地址： 的本地化字符串。
        /// </summary>
        internal static string Form1_pathTextE_Text {
            get {
                return ResourceManager.GetString("Form1.pathTextE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入文件目录： 的本地化字符串。
        /// </summary>
        internal static string Form1_pathTextI_Text {
            get {
                return ResourceManager.GetString("Form1.pathTextI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择你要导入/导出的常规飞船： 的本地化字符串。
        /// </summary>
        internal static string Form1_seedSelectText_Text {
            get {
                return ResourceManager.GetString("Form1.seedSelectText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你可在此处导出/入飞船文件： 的本地化字符串。
        /// </summary>
        internal static string Form1_seedShipIOText_Text {
            get {
                return ResourceManager.GetString("Form1.seedShipIOText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船种子： 的本地化字符串。
        /// </summary>
        internal static string Form1_seedText_Text {
            get {
                return ResourceManager.GetString("Form1.seedText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择你要覆盖的飞船: 的本地化字符串。
        /// </summary>
        internal static string Form1_shipSelectI_Text {
            get {
                return ResourceManager.GetString("Form1.shipSelectI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏存档 的本地化字符串。
        /// </summary>
        internal static string Form1_tabPage1_Text {
            get {
                return ResourceManager.GetString("Form1.tabPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义飞船 的本地化字符串。
        /// </summary>
        internal static string Form1_tabPage2_Text {
            get {
                return ResourceManager.GetString("Form1.tabPage2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规飞船 的本地化字符串。
        /// </summary>
        internal static string Form1_tabPage3_Text {
            get {
                return ResourceManager.GetString("Form1.tabPage3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无人深空飞船导入与导出工具 的本地化字符串。
        /// </summary>
        internal static string Form1_this_Text {
            get {
                return ResourceManager.GetString("Form1.this.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅找到一个存档，自动选择  的本地化字符串。
        /// </summary>
        internal static string 仅找到一个存档_自动选择 {
            get {
                return ResourceManager.GetString("仅找到一个存档_自动选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档加载完成。 的本地化字符串。
        /// </summary>
        internal static string 存档加载完成 {
            get {
                return ResourceManager.GetString("存档加载完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档平台： 的本地化字符串。
        /// </summary>
        internal static string 存档平台 {
            get {
                return ResourceManager.GetString("存档平台", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寻找存档失败，错误信息： 的本地化字符串。
        /// </summary>
        internal static string 寻找存档失败_错误信息 {
            get {
                return ResourceManager.GetString("寻找存档失败_错误信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待加载 的本地化字符串。
        /// </summary>
        internal static string 待加载 {
            get {
                return ResourceManager.GetString("待加载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作取消！ 的本地化字符串。
        /// </summary>
        internal static string 操作取消 {
            get {
                return ResourceManager.GetString("操作取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持文件（*.json；*.sh0；*.nmsship；*.tech）|*.json; *.sh0; *.nmsship; *.tech|所有文件（*.*）|*.* 的本地化字符串。
        /// </summary>
        internal static string 文件筛选内容A {
            get {
                return ResourceManager.GetString("文件筛选内容A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持文件（*.json；*.nmsship）|*.json; *nmsship|所有文件|*.* 的本地化字符串。
        /// </summary>
        internal static string 文件筛选内容BS {
            get {
                return ResourceManager.GetString("文件筛选内容BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持文件（*.json；*.sh0；*.nmsship）|*.json; *.sh0; *.nmsship|所有文件（*.*）|*.* 的本地化字符串。
        /// </summary>
        internal static string 文件筛选内容S {
            get {
                return ResourceManager.GetString("文件筛选内容S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持文件（*.json；*.tech）|*.json; *.tech|所有文件 (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string 文件筛选内容T {
            get {
                return ResourceManager.GetString("文件筛选内容T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还未选择导入内容或输入内容！请选择你要导入的文件或手动输入导入的内容！ 的本地化字符串。
        /// </summary>
        internal static string 无导入内容 {
            get {
                return ResourceManager.GetString("无导入内容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后保存时间： 的本地化字符串。
        /// </summary>
        internal static string 最后保存时间 {
            get {
                return ResourceManager.GetString("最后保存时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未命名 的本地化字符串。
        /// </summary>
        internal static string 未命名 {
            get {
                return ResourceManager.GetString("未命名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到有效的存档 的本地化字符串。
        /// </summary>
        internal static string 没有找到有效的存档 {
            get {
                return ResourceManager.GetString("没有找到有效的存档", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家存档 的本地化字符串。
        /// </summary>
        internal static string 玩家存档 {
            get {
                return ResourceManager.GetString("玩家存档", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string 确定 {
            get {
                return ResourceManager.GetString("确定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 种子无效 的本地化字符串。
        /// </summary>
        internal static string 种子无效 {
            get {
                return ResourceManager.GetString("种子无效", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string 警告 {
            get {
                return ResourceManager.GetString("警告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择一个选项！ 的本地化字符串。
        /// </summary>
        internal static string 请先选择一个选项 {
            get {
                return ResourceManager.GetString("请先选择一个选项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个选项 的本地化字符串。
        /// </summary>
        internal static string 请选择一个选项 {
            get {
                return ResourceManager.GetString("请选择一个选项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个存档 的本地化字符串。
        /// </summary>
        internal static string 选择一个存档 {
            get {
                return ResourceManager.GetString("选择一个存档", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string 错误 {
            get {
                return ResourceManager.GetString("错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入内容不是合法的 JSON 格式！ 的本地化字符串。
        /// </summary>
        internal static string 非法JSON格式 {
            get {
                return ResourceManager.GetString("非法JSON格式", resourceCulture);
            }
        }
    }
}
